# Default values for eyra-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ''
fullnameOverride: ''

domain: staging.eyrabenchmark.net

web:
  debug: 'True'
  imageName: 'eyra/comic:89'
  emailAddres: 'eyra.benchmark@gmail.com'
  emailHost: 'smtp.gmail.com'
  emailPort: '587'
  emailUseTLS: 'True'
  environment: 'staging'

eyra-frontend:
  image:
    repository: eyra/frontend
    tag: 551
    pullPolicy: IfNotPresent

  nameOverride: ''
  fullnameOverride: ''

  EYRA_BACKEND_URL: 'https://api.staging.eyrabenchmark.net/api/v1/'

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      kubernetes.io/tls-acme: 'true'
      certmanager.k8s.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: 'nginx'
    #      kubernetes.io/ingress.class: alb
    #      alb.ingress.kubernetes.io/scheme: internet-facing
    paths:
      - /
    hosts:
      - staging.eyrabenchmark.net
      - www.staging.eyrabenchmark.net
    tls:
      - secretName: staging.eyrabenchmark.net-tls
        hosts:
          - staging.eyrabenchmark.net
      - secretName: www.staging.eyrabenchmark.net-tls
        hosts:
          - www.staging.eyrabenchmark.net

  nodeSelector: {}

  tolerations: []

  affinity: {}


postgresql:
  existingSecret: eyra-postgresql
  postgresqlUsername: comic
  postgresqlDatabase: comic
  initdbScripts:
    setup.sql: |
      ALTER USER comic WITH SUPERUSER;

redis:
  usePassword: false
  cluster:
    enabled: false

s3:
  region: eu-central-1
  bucket: eyra-data01
  host: s3.eu-central-1.amazonaws.com

replicaCount: 1

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

docker-registry:
  storage: s3
  s3:
    region: eu-central-1
    regionEndpoint: s3.eu-central-1.amazonaws.com
    bucket: eyra-data01
    encrypt: false
    secure: true

  secrets:
    s3:
      accessKey:
      secretKey:

tags:
  memcached: false

eyra-jupyter:
  enabled: true
  image:
    repository: eyra/jupyter
    tag: latest
    pullPolicy: IfNotPresent

  nameOverride: ''
  fullnameOverride: ''

  JUPYTER_USER: 'eyra'
  JUPYTER_PASSWORD: 'eyra'

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: 'true'
      kubernetes.io/tls-acme: 'true'
      certmanager.k8s.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: 'nginx'
    paths:
      - /
    hosts:
      - jupyter.staging.eyrabenchmark.net
    tls:
      - secretName: jupyter.staging.eyrabenchmark.net-tls
        hosts:
          - jupyter.staging.eyrabenchmark.net

  nodeSelector: {}

  tolerations: []

  affinity: {}

  postgresql:
    existingSecret: eyra-postgresql
    postgresqlUsername: comic
    postgresqlDatabase: comic

  s3:
    region: eu-central-1
    bucket: eyra-data01
    host: s3.eu-central-1.amazonaws.com
