# Default values for eyra-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

postgresql:
  existingSecret: eyra-postgresql
  postgresqlUsername: comic
  postgresqlDatabase: comic
  initdbScripts:
    setup.sql: |
      ALTER USER comic WITH SUPERUSER;

redis:
  usePassword: false
  cluster:
    enabled: false

web:
  debug: "True"
  siteID: "2"
  travisBuildID: 2188-eyra-master
  emailAddres: "eyra.benchmark@gmail.com"
  emailHost: "smtp.gmail.com"
  emailPort: '587'
  emailUseTLS: 'True'
  mainProjectName: 'grand-challenges'
  subdomainIsProjectName: "True"

docker-registry:
  persistence:
    enabled: true
    size: 10Gi

minio:
  existingSecret: "eyra-minio"

dev:
  name: "roel"
  namespace: "dev-roel"

domain: roel.dev.eyrabenchmark.net

replicaCount: 1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

eyra-frontend:
  image:
    repository: eyra/frontend
    tag: 151
    pullPolicy: IfNotPresent

  nameOverride: ""
  fullnameOverride: ""

  BACKEND_URL: "https://api.roel.dev.eyrabenchmark.net"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: "nginx"
    paths:
    - /
    hosts:
    - roel.dev.eyrabenchmark.net
    - www.roel.dev.eyrabenchmark.net
    tls:
    - secretName: roel.dev.eyrabenchmark.net-tls
      hosts:
      - roel.dev.eyrabenchmark.net
    - secretName: www.roel.dev.eyrabenchmark.net-tls
      hosts:
      - www.roel.dev.eyrabenchmark.net


  nodeSelector: {}

  tolerations: []

  affinity: {}
