apiVersion: v1
kind: Service
metadata:
  name: {{ include "eyra-frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eyra-frontend.name" . }}
    helm.sh/chart: {{ include "eyra-frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "eyra-frontend.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

