image:
  repository: eyra/frontend
  tag: 151
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

BACKEND_URL: "https://api.tom.dev.eyrabenchmark.net"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
  paths:
    - /
  hosts:
    - tom.dev.eyrabenchmark.net
    - www.tom.dev.eyrabenchmark.net
  tls:
    - secretName: tom.dev.eyrabenchmark.net-tls
      hosts:
        - tom.dev.eyrabenchmark.net
    - secretName: www.tom.dev.eyrabenchmark.net-tls
      hosts:
        - www.tom.dev.eyrabenchmark.net


nodeSelector: {}

tolerations: []

affinity: {}
