apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: celery-flower-service
  name: celery-flower-service
spec:
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  selector:
    io.kompose.service: celery-flower
status:
  loadBalancer: {}
