apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: celery-worker
  name: celery-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - config
        - worker
        - -l
        - info
        - -c
        - "1"
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis-service:6379
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_USER
        image: grandchallenge/web:2099-eyra-master
        name: celery-worker
        resources: {}
      restartPolicy: Always
status: {}
