apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    app: web
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web
        io.kompose.service: web
    spec:
      containers:
      - args:
        - bash
        - -c
        - ' gunicorn -w 4 -b 0.0.0.0 config.wsgi '
        env:
        - name: CELERY_BROKER_URL
          value: redis://redis-service:6379
        - name: CSRF_COOKIE_SECURE
          value: "True"
        - name: DEBUG
          value: "True"
        - name: DEFAULT_FROM_EMAIL
          value: 'eyra.benchmark@gmail.com'
        - name: DJANGO_ADMIN_URL
          value: admin
        - name: DJANGO_SENTRY_DSN
          value: https://ad4b4cf5222944519702ecb13bd565c1@sentry.io/1326705
        - name: EMAIL_HOST
          value: "smtp.gmail.com"
        - name: EMAIL_HOST_PASSWORD
          value: 'KAj@ELvo*5c3hQf0'
        - name: EMAIL_HOST_USER
          value: 'eyra.benchmark@gmail.com'
        - name: EMAIL_PORT
          value: '587'
        - name: EMAIL_USE_TLS
          value: 'True'
        - name: GOOGLE_ANALYTICS_ID
          value: 'UA-XXXXX-Y'
        - name: GOOGLE_MAPS_API_KEY
          value: 'CHANGEME!!!'
        - name: MAIN_HOST_NAME
          value: https://384c82ad-a82b-40d3-a8ed-17965c0b61b3.k8s.ondigitalocean.com
        - name: MAIN_PROJECT_NAME
          value: grand-challenges
        - name: MANAGER_EMAIL
          value: 'eyra.benchmark@gmail.com'
        - name: MEDIA_ROOT
          value: /dbox/Dropbox/comicframework/
        - name: POSTGRES_HOST
          value: postgres-service
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-db
              key: POSTGRES_USER
        - name: SECRET_KEY
          value: 'p$$^$$w*1*q!fchwr1r6c%4asb5*js14p)wm1z+1e)a%jyze9=d='
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_CONTENT_TYPE_NOSNIFF
          value: "True"
        - name: SECURE_HSTS_INCLUDE_SUBDOMAINS
          value: "True"
        - name: SECURE_HSTS_SECONDS
          value: "3600"
        - name: SERVER_EMAIL
          value: 'eyra.benchmark@gmail.com'
        - name: SESSION_COOKIE_DOMAIN
          value: .staging.eyrabenchmark.net 
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: SITE_ID
          value: "2"
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          value: ''
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          value: ''
        - name: SUBDOMAIN_IS_PROJECTNAME
          value: "True"
        - name: WHITENOISE
          value: "True"
        - name: X_FRAME_OPTIONS
          value: DENY
        image: grandchallenge/web:2099-eyra-master
        #        livenessProbe:
        # exec:
        #   command:
        #   - curl http://web:8000/ || exit 1
        # failureThreshold: 5
        # periodSeconds: 10
        # timeoutSeconds: 5
        name: web
        resources: {}
        #volumeMounts:
        #- mountPath: /static/
        #  name: static-claim0
      restartPolicy: Always
      #      volumes:
      #- name: static-claim0
      #  persistentVolumeClaim:
      #    claimName: static-claim0
status: {}
