apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-celery-flower
    helm.sh/chart: {{ include "eyra.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-celery-flower
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery-flower
    spec:
      containers:
      - env:
        - name: CELERY_BROKER_URL
          value: redis://{{ .Release.Name }}-redis-master:6379/0
        image: crgwbr/docker-celery-flower
        name: {{ .Release.Name }}-celery-flower
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
