apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
    helm.sh/chart: {{ include "eyra.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-celery-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-celery-worker
    spec:
      containers:
      - args:
        - celery
        - -A
        - config
        - worker
        - -l
        - info
        - -c
        - "1"
        env:
        - name: CELERY_BROKER_URL
          value: redis://{{ .Release.Name }}-redis-master:6379
        - name: POSTGRES_HOST
          value: '{{ .Release.Name }}-postgresql'
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        image: grandchallenge/web:{{ .Values.web.travisBuildID }}
        name: {{ .Release.Name }}-celery-worker
        resources: {}
      restartPolicy: Always
status: {}
