apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-celery-beat
    helm.sh/chart: {{ include "eyra.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-celery-beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eyra.name" . }}-celery-beat
    spec:
      containers:
      - args:
        - celery
        - -A
        - config
        - beat
        - -l
        - info
        - --scheduler
        - django_celery_beat.schedulers:DatabaseScheduler
        - --pidfile=/tmp/celerybeat.pid
        env:
        - name: CELERY_BROKER_URL
          value: redis://{{ .Release.Name }}-redis-master:6379
        - name: POSTGRES_HOST
          value: '{{ .Release.Name }}-postgresql'
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        - name: POSTGRESQL_HOST
          value: '{{ .Release.Name }}-postgresql'
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRESQL_USERNAME
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        # todo: remove after prod backend update:
        - name: SENTRY_DISABLE
          value: "False"
        image: {{ .Values.web.imageName }}
        name: celery-beat
        resources: {}
      restartPolicy: Always
status: {}
