apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: celery-beat
  name: celery-beat
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: celery-beat
    spec:
      containers:
      - args:
        - celery
        - -A
        - config
        - beat
        - -l
        - info
        - --scheduler
        - django_celery_beat.schedulers:DatabaseScheduler
        - --pidfile=/tmp/celerybeat.pid
        env:
        - name: CELERY_BROKER_URL
          value: redis://eyra-redis-master:6379
        - name: POSTGRES_HOST
          value: eyra-postgresql
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        image: grandchallenge/web:{{ .Values.web.travisBuildID }}
        name: celery-beat
        resources: {}
      restartPolicy: Always
status: {}
