apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-celery-flower
    helm.sh/chart: {{ include "eyra.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-celery-flower
spec:
  ports:
  - protocol: TCP
    port: 5555
    targetPort: 5555
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-celery-flower
status:
  loadBalancer: {}
