{{- if .Values.dev -}}
{{- if .Values.dev.name -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.dev.name }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-admin
rules:
- apiGroups: ["", "extensions", "apps", "batch"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.dev.name }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-admin
subjects:
- kind: User
  name: system:serviceaccount:{{ .Values.dev.namespace }}:{{ .Values.dev.name }}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
{{ end }}
