apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-web
    helm.sh/chart: {{ include "eyra.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
        app.kubernetes.io/name: {{ .Release.Name }}-web
    spec:
      containers:
      - args:
        - bash
        - -c
        - ' gunicorn -w 4 -b 0.0.0.0 config.wsgi '
        env:
        - name: CELERY_BROKER_URL
          value: redis://{{ .Release.Name }}-redis-master:6379
        - name: CSRF_COOKIE_SECURE
          value: "True"
        - name: DEBUG
          value: '{{ .Values.web.debug }}'
        - name: DEFAULT_FROM_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: DJANGO_ADMIN_URL
          value: admin
        - name: DJANGO_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: eyra-sentry
              key: dsn
        - name: EMAIL_HOST
          value: '{{ .Values.web.emailHost }}'
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-gmail
              key: password
        - name: EMAIL_HOST_USER
          value: '{{ .Values.web.emailAddress }}'
        - name: EMAIL_PORT
          value: '{{ .Values.web.emailPort }}'
        - name: EMAIL_USE_TLS
          value: '{{ .Values.web.emailUseTLS }}'
        - name: GOOGLE_ANALYTICS_ID
          valueFrom:
            secretKeyRef:
              name: eyra-google-analytics
              key: googleAnalyticsID
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: eyra-google-maps
              key: apiKey
        - name: MAIN_PROJECT_NAME
          value: '{{ .Values.web.mainProjectName }}'
        - name: MANAGER_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: MEDIA_ROOT
          value: /dbox/Dropbox/comicframework/
        - name: POSTGRES_HOST
          value: '{{ .Release.Name }}-postgresql'
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        - name: S3_ENDPOINT_URL
          valueFrom:
            secretKeyRef:
              name: do-spaces
              key: endpoint
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: do-spaces
              key: key
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: do-spaces
              key: secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: eyra-django
              key: secretKey
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_CONTENT_TYPE_NOSNIFF
          value: "True"
        - name: SECURE_HSTS_INCLUDE_SUBDOMAINS
          value: "True"
        - name: SECURE_HSTS_SECONDS
          value: "3600"
        - name: SERVER_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: SESSION_COOKIE_DOMAIN
          value: .{{ .Values.domain }}
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: SITE_ID
          value: '{{ .Values.web.siteID }}'
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          valueFrom:
            secretKeyRef:
              optional: true
              name: eyra-social-auth-google
              key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          valueFrom:
            secretKeyRef:
              optional: true
              name: eyra-social-auth-google
              key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        - name: SUBDOMAIN_IS_PROJECTNAME
          value: '{{ .Values.web.subdomainIsProjectName }}'
        - name: WHITENOISE
          value: "True"
        - name: X_FRAME_OPTIONS
          value: DENY
        image: grandchallenge/web:{{ .Values.web.travisBuildID }}
        name: web
        resources: {}
      restartPolicy: Always
status: {}
