apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress-comic
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - comic.staging.eyrabenchmark.net
    secretName: web-ingress-comic-letsencrypt

  rules:
  - host: comic.staging.eyrabenchmark.net
    http:
      paths:
      - path: /
        backend:
          serviceName: web-service
          servicePort: 8000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: "nginx"
  name: web-ingress-api
spec:
  tls:
  - hosts:
    - api.staging.eyrabenchmark.net
    secretName: web-ingress-api-letsencrypt
  rules:
  - host: api.staging.eyrabenchmark.net
    http:
      paths:
      - backend:
          serviceName: web-service
          servicePort: 8000
        path: /api/v1
