apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-web-migrations"
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: {{ include "eyra.chart" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}-web-migrations"
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: {{ .Values.web.imageName }}
        args:
        - bash
        - -c
        - ' python manage.py migrate'
        env:
        - name: CELERY_BROKER_URL
          value: redis://{{ .Release.Name }}-redis-master:6379
        - name: CSRF_COOKIE_SECURE
          value: "True"
        - name: DEBUG
          value: '{{ .Values.web.debug }}'
        - name: DEFAULT_FROM_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: DJANGO_ADMIN_URL
          value: admin
        - name: DJANGO_SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: eyra-sentry
              key: dsn
        - name: EMAIL_HOST
          value: '{{ .Values.web.emailHost }}'
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-gmail
              key: password
        - name: EMAIL_HOST_USER
          value: '{{ .Values.web.emailAddress }}'
        - name: EMAIL_PORT
          value: '{{ .Values.web.emailPort }}'
        - name: EMAIL_USE_TLS
          value: '{{ .Values.web.emailUseTLS }}'
        - name: GOOGLE_ANALYTICS_ID
          valueFrom:
            secretKeyRef:
              name: eyra-google-analytics
              key: googleAnalyticsID
        - name: GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: eyra-google-maps
              key: apiKey
        - name: MAIN_PROJECT_NAME
          value: '{{ .Values.web.mainProjectName }}'
        - name: MANAGER_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: MEDIA_ROOT
          value: /dbox/Dropbox/comicframework/
        - name: POSTGRES_HOST
          value: '{{ .Release.Name }}-postgresql'
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: eyra-postgresql
              key: postgresql-password
        - name: S3_HOST
          value: {{ .Values.s3.host | quote }}
        - name: S3_REGION
          value: {{ .Values.s3.region | quote }}
        - name: S3_BUCKET
          value: {{ .Values.s3.bucket | quote }}
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: eyra-django
              key: secretKey
        # todo: remove after prod backend update:
        - name: SENTRY_DISABLE
          value: "False"
        - name: K8S_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: PRIVATE_DOCKER_REGISTRY
          value: docker-registry.{{ .Values.domain }}
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_CONTENT_TYPE_NOSNIFF
          value: "True"
        - name: SECURE_HSTS_INCLUDE_SUBDOMAINS
          value: "True"
        - name: SECURE_HSTS_SECONDS
          value: "3600"
        - name: SERVER_EMAIL
          value: {{ .Values.web.emailAddress }}
        - name: SESSION_COOKIE_DOMAIN
          value: .{{ .Values.domain }}
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: SITE_ID
          value: '{{ .Values.web.siteID }}'
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
          valueFrom:
            secretKeyRef:
              optional: true
              name: eyra-social-auth-google
              key: SOCIAL_AUTH_GOOGLE_OAUTH2_KEY
        - name: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
          valueFrom:
            secretKeyRef:
              optional: true
              name: eyra-social-auth-google
              key: SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET
        - name: SUBDOMAIN_IS_PROJECTNAME
          value: '{{ .Values.web.subdomainIsProjectName }}'
        - name: WHITENOISE
          value: "True"
        - name: X_FRAME_OPTIONS
          value: DENY