apiVersion: v1
kind: Pod
metadata:
  name: test-gpu
spec:
  containers:
  - image: eyra/frb-astro-accelerate:3
    name: test-gpu-container
    command: ["sleep"]
    args: ["3600000"]
    volumeMounts:
    - mountPath: /data
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: temp-pv-claim
  nodeSelector:
    kubernetes.io/hostname: ip-10-0-0-75.eu-central-1.compute.internal
    # kubernetes.io/hostname: ip-10-0-1-33.eu-central-1.compute.internal
    # kubernetes.io/hostname: ip-10-0-1-126.eu-central-1.compute.internal
    # kubernetes.io/hostname: ip-10-0-0-110.eu-central-1.compute.internal
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: temp-pv-claim
spec:
  #  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

