{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  jupyterhub_config.py: |
    {{ .Files.Get "jupyterhub_config.py" | indent 4 }}
  entrypoint.sh: |
    {{ .Files.Get "entrypoint.sh" | indent 4 }}
{{- end }}