{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eyra-jupyter.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "eyra-jupyter.name" . }}
    helm.sh/chart: {{ include "eyra-jupyter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eyra-jupyter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eyra-jupyter.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: JUPYTER_USER
            value: "{{ .Values.JUPYTER_USER }}"
          - name: JUPYTER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eyra-jupyter
                key: password
          - name: CELERY_BROKER_URL
            value: redis://{{ .Release.Name }}-redis-master:6379
          - name: MEDIA_ROOT
            value: /dbox/Dropbox/comicframework/
          - name: POSTGRES_HOST
            value: '{{ .Release.Name }}-postgresql'
          - name: POSTGRES_DB
            value: {{ .Values.postgresql.postgresqlDatabase }}
          - name: POSTGRES_USER
            value: {{ .Values.postgresql.postgresqlUsername }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: eyra-postgresql
                key: postgresql-password
          - name: S3_HOST
            value: {{ .Values.s3.host | quote }}
          - name: S3_REGION
            value: {{ .Values.s3.region | quote }}
          - name: S3_BUCKET
            value: {{ .Values.s3.bucket | quote }}
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: eyra-django
                key: secretKey
          - name: SENTRY_DISABLE
            value: 'True'
          - name: K8S_NAMESPACE
            value: {{ .Release.Namespace }}
          - name: PRIVATE_DOCKER_REGISTRY
            value: docker-registry.{{ .Values.domain }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /home/{{ .Values.JUPYTER_USER }}
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: jupyter-pv-claim

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}